### ISSUE TITLE
IIPC Web Archiving Conference 2024

### ISSUE THREAD

**Issue by chartgerink** [libscie/.github#10]

**Comment by chartgerink** [comment]
@MayaAndersonGonzalez - I did not know this conference existed until you mentioned it!

Were there any things that resonated particularly with you, while you attended the conference?

**Comment by MayaAndersonGonzalez** [comment]
@chartgerink yes definitely !

1. https://scholar.archive.org/about and their partnership potential
2. the idea of curated collections (which ties into the idea of content moderation)
3. Researcher-curator collaboration to create "guided tours" as a gateway into collections for the unfamiliar user/public.

Happy May Day! 🪅

**Comment by chartgerink** [comment]
Thanks @MayaAndersonGonzalez, for sharing your reflections 😊 

I will close the issue, but feel free to comment here if you have any further reflections on the conference.
