### ISSUE TITLE
Open Science Retreat NL 2024

### ISSUE THREAD

**Issue by chartgerink** [libscie/.github#4]

**Comment by chartgerink** [comment]
@nsunami and @MayaAndersonGonzalez if we want to coordinate any plans, we can do so here as well (mind you it is public). Is it okay if I assign you on this issue to indicate your attendance?

I am thinking about spending the retreat to work on version 2 of ResearchEquals mostly. Maybe we can run some brainstorms on specifics like content moderation or community review?

**Comment by MayaAndersonGonzalez** [comment]
Absolutely, count me in ! 👍

**Comment by nsunami** [comment]
@chartgerink Yes!

**Comment by chartgerink** [comment]
Is there any additional things you might want to discuss during this week? 

We already had some conversations around:

* [Content moderation](https://github.com/orgs/libscie/projects/6/views/1?pane=issue&itemId=57830890)
* [Feedback: an alternative to peer review](https://github.com/orgs/libscie/projects/6/views/1?pane=issue&itemId=57830854)
* [Personas non grata](https://github.com/orgs/libscie/projects/6/views/1?pane=issue&itemId=57837666)

I am working a bit on the new version of ResearchEquals, getting things in place and primarily thinking about the design and marketing at this point. You can see some (limited) new design direction over at <dev.researchequals.com> from here on out.

**Comment by chartgerink** [comment]
Closing the issue as the event ended, but will not lock  it in case people want to share anything else.

There is also [a ResearchEquals collection for the event](https://doi.org/10.53962/mrhg-9r), if there's anything you still want to submit 😊 

Was amazing to get to spend time with both of you 💜
