### ISSUE TITLE
Open Science Festival NL 2024

### ISSUE THREAD

**Issue by chartgerink** [libscie/.github#5]
Who is going to the Open Science Festival in the Netherlands on October 22nd? I am still debating it as it is a Tuesday and I'd have to take time off from my dayjob (including travel).

**Comment by chartgerink** [comment]
Okay it looks like I'll be joining. 😊 cc @nsunami @AnnaVantVeer @hanneoberman who else will be there 😄?

**Comment by chartgerink** [comment]
Session submissions are possible now 👍 Registration will open June 21st

https://opensciencefestival.nl/en/news/call-for-sessions-national-open-science-festival-opened

**Comment by AnnaVantVeer** [comment]
yes, I will be there! and, don't forget to book a hotel because you are all needed at the BARCAMP the day before as well! See https://www.linkedin.com/feed/update/urn:li:activity:7207346355701174274/

**Comment by chartgerink** [comment]
Our session with @karvovskaya is accepted! It'll be about our work on https://github.com/ubvu/open-handbook 👍

**Comment by chartgerink** [comment]
We had a blog post as a follow-up: https://upstream.force11.org/cultivating-openness-from-community-resources-to-institutional-acceptance/

Pictures are now available here: https://www.flickr.com/photos/201765692@N04/sets/72177720321740875/
